all: false
dir: "{{.InterfaceDir}}/mocks"
filename: "mock_{{.InterfaceName | lower }}.go"
packages:
  github.com/kriuchkov/tock/internal/core/ports:
    interfaces:
      ActivityResolver:
      ActivityRepository: